---
# Source: ei-pattern-1/charts/mysql-ei/charts/mysql/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2ei-rdbms-service-mysql
  namespace: wso2-ei
  labels:
    app: wso2ei-rdbms-service-mysql
    chart: "mysql-1.6.9"
    release: "wsoei"
    heritage: "Helm"

spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wso2ei-rdbms-service-mysql
      release: wsoei
  template:
    metadata:
      labels:
        app: wso2ei-rdbms-service-mysql
        release: wsoei
    spec:
      serviceAccountName: default
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.32"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      # - name: do-something
      #   image: busybox
      #   command: ['do', 'something']
      
      containers:
      - name: wso2ei-rdbms-service-mysql
        image: "mysql:5.7"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wso2ei-rdbms-service-mysql
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wso2ei-rdbms-service-mysql
              key: mysql-password
        - name: MYSQL_USER
          value: "wso2carbon"
        - name: MYSQL_DATABASE
          value: ""
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: configurations
          mountPath: /etc/mysql/conf.d/mysql.cnf
          subPath: mysql.cnf
        - name: migrations
          mountPath: /docker-entrypoint-initdb.d
        # - name: extras
        #   mountPath: /usr/share/extras
        #   readOnly: true
        
      volumes:
      - name: configurations
        configMap:
          name: wso2ei-rdbms-service-mysql-configuration
      - name: migrations
        configMap:
          name: wso2ei-rdbms-service-mysql-initialization
      - name: data
        persistentVolumeClaim:
          claimName: wso2ei-rdbms-service-mysql
      # - name: extras
      #   emptyDir: {}
