---
# Source: ei-pattern-1/charts/mysql-ei/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wso2ei-rdbms-service-mysql
  namespace: wso2-ei
  labels:
    app: wso2ei-rdbms-service-mysql
    chart: "mysql-1.6.9"
    release: "wsoei"
    heritage: "Helm"
type: Opaque
data:
  
  mysql-root-password:  "cm9vdA=="
  
  
  mysql-password:  "d3NvMmNhcmJvbg=="
